# Generated by Django 4.2.30 on 2026-09-16 07:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PTMEvent',
            fields=[
                ('tenant_id', models.CharField(help_text='ID of the school/ERP tenant', max_length=100)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('slot_duration_minutes', models.PositiveIntegerField(default=15)),
                ('gap_duration_minutes', models.PositiveIntegerField(default=5)),
                ('mode', models.CharField(choices=[('IN_PERSON', 'In Person'), ('VIRTUAL', 'Virtual'), ('HYBRID', 'Hybrid')], default='IN_PERSON', max_length=20)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PTMSlot',
            fields=[
                ('tenant_id', models.CharField(help_text='ID of the school/ERP tenant', max_length=100)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('teacher_id', models.CharField(help_text='External ID of the teacher', max_length=100)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('room_number', models.CharField(blank=True, max_length=50, null=True)),
                ('meeting_link', models.URLField(blank=True, null=True)),
                ('is_booked', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='ptm.ptmevent')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='PTMBooking',
            fields=[
                ('tenant_id', models.CharField(help_text='ID of the school/ERP tenant', max_length=100)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_id', models.CharField(help_text='External ID of the student', max_length=100)),
                ('parent_id', models.CharField(help_text='External ID of the parent', max_length=100)),
                ('parent_pre_query', models.TextField(blank=True, help_text='Pre-meeting query submitted by parent', null=True)),
                ('status', models.CharField(choices=[('BOOKED', 'Booked'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('NO_SHOW', 'No Show'), ('CANCELLED', 'Cancelled')], default='BOOKED', max_length=20)),
                ('teacher_remarks', models.TextField(blank=True, help_text='Shared feedback visible to parent', null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('slot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='ptm.ptmslot')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
